version: 1
trigger:
  paths:
    - /Users/sneo/dev/code/backend/biblioteka/
action:
  what: serve
  workdir: /Users/sneo/dev/code/backend/biblioteka/
  exec: bash
  args:
    - -c
    - for i in {1..100}; do echo line $i; sleep 1; done
output: 
  mode: file
  path: /Users/sneo/output.txt

